name: audioplayers_test_server
resolution: workspace
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  async: ^2.13.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3

dev_dependencies:
  flame_lint: ^1.4.2
  http: ^1.5.0
